name: potato_notes
description: Official POSP note app
version: 1.5.2+15

environment:
  sdk: '>=2.2.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  path_provider:
  outline_material_icons:
  community_material_icon:
  flutter_staggered_grid_view:
  spicy_components:
    git: https://github.com/HrX03/SpicyUIComponents

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true